version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/examples/pubspec.yaml"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/open_xml/pubspec.yaml"
    schedule:
      interval: "daily"
